### ISSUE TITLE
Suggestion for Blue Mage bars

### ISSUE THREAD

**Issue by MikeOrtizzz** [0ceal0t/JobBars#10]
Nightbloom and Song Of Torment dot's are a crucial part of the Blue Mage's gameplay and since they cannot be stack with each other maybe they can be on the same bar? even just having Nightbloom as a stand alone bar would be enough. There is also Bad Breath (Malodorous debuff) and Condensed Libra (Random debuff from a set of 3) timers for BLU tanks since they need to be reapply just like dot's. 

Libra tracking (Something like the VerSone/VerFire proc tracker. It should tell you what debuff of the posible 3 is currently on) or Cold Fog timer would be nice but just the Nightbloom timer is a must.

**Comment by 0ceal0t** [comment]
https://github.com/0ceal0t/JobBars/commit/f2fdbc09574b668e675d676a326f9eebfa14e738, will be in the next update

- Added nightbloom to the song of torment bar and extended the bar to 60 seconds. I left nightbloom off of the icon replace list, since you'll probably want to see its actual cooldown
- Added bad breath timer
- Added condensed libra proc tracker
