### ISSUE TITLE
GCD under Buff tracker for White Mage's Presence of Mind

### ISSUE THREAD

**Issue by AmberAvemour** [0ceal0t/JobBars#29]
Not super important but for the sake of feature suggesting, I found the GCD trackers for other jobs cooldowns really useful for making sure i'm fitting everything in and it would be helpful if there was also one for White Mage's DPS cooldown

**Comment by 0ceal0t** [comment]
I'll ask around to see if other people would find something like that useful. My initial impression, however, is that it's not as helpful as tracking GCDs under other buffs, since it isn't strictly a damage buff, but a cast speed increase.

I might add it as a timer similar to lightspeed on AST. Either way, thanks for the feedback!

**Comment by 0ceal0t** [comment]
added PoM as a timer: https://github.com/0ceal0t/JobBars/commit/d5e3c16ccf0cb1f9abbce11815ef7ed49ca0f6a8
