### ISSUE TITLE
Disembowel gauge

### ISSUE THREAD

**Issue by Warakia8912** [0ceal0t/JobBars#34]
Would DRG's Disembowel gauge be possible? I think it might become useful like other melee DPS' damage buff represented as a gauge. Thank you!

**Comment by 0ceal0t** [comment]
I tried adding this, but most people didn't find it very useful. Disembowel and Chaos thrust get refreshed naturally during DRG's rotation, so knowing the time left on it usually isn't helpful.

It's a bit different than MNK, since that job can potentially change slightly depending on the time left on twin snakes. As far as I understand, this isn't the case with DRG

**Comment by Warakia8912** [comment]
Thank you so much for your fast response! Personally I'd love to have it as an option that can be enabled (at least for me), but I understand your reasoning and if your final decision is a no, then I'll respect it. Thank you again!
